### ISSUE TITLE
main property target is wrong 

### ISSUE THREAD

**Issue by sebaplaza** [emahnovets/jsdom-to-image#9]
**Describe the bug**

I can't use the package, because is marked as not found by my test runner.

**To Reproduce**

```sh
npm add jsdom-to-image
```

try to import the module as usual

```js
import { setGlobalOptions } from 'jsdom-to-image';

setGlobalOptions({
	connectOptions: {
		browserWSEndpoint: 'ws://localhost:9090',
	},
});

```

You get 

```sh
    Cannot find module 'jsdom-to-image' from 'jest.setup.ts'
```

**Expected behavior**

should import the module

**Additional context**

Problem comes from `package.json` **main** and **types** properties

```json
{
  "name": "jsdom-to-image",
  "version": "1.1.0",
  "description": "Generale image from JSDOM",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
}
```

They should be instead

```json
{
  "name": "jsdom-to-image",
  "version": "1.1.0",
  "description": "Generale image from JSDOM",
  "main": "dist/src/index.js",
  "types": "dist/src/index.d.ts",
}
```

**Comment by Merri** [comment]
There is a mistake in the project that it is built with the same `tsconfig.json` as is used for development. Earlier on the project had only `src` included so it didn't generate any sub-directories, but now that there are more directories each is generated into their own one respectively.

Current workaround is to import from `jsdom-to-image/dist/src' but that isn't very ideal.
